// This file is auto-generated by @hey-api/openapi-ts

export const AppointmentCreateSchema = {
    properties: {
        doctor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Doctor Id'
        },
        patient_name: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Name'
        },
        patient_phone: {
            type: 'string',
            maxLength: 20,
            title: 'Patient Phone'
        },
        patient_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Email'
        },
        contact_method: {
            '$ref': '#/components/schemas/ContactMethod',
            default: 'phone'
        },
        appointment_date: {
            type: 'string',
            format: 'date',
            title: 'Appointment Date'
        },
        appointment_time: {
            type: 'string',
            maxLength: 5,
            title: 'Appointment Time'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['doctor_id', 'patient_name', 'patient_phone', 'appointment_date', 'appointment_time'],
    title: 'AppointmentCreate'
} as const;

export const AppointmentPublicSchema = {
    properties: {
        doctor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Doctor Id'
        },
        patient_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Id'
        },
        patient_name: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Name'
        },
        patient_phone: {
            type: 'string',
            maxLength: 20,
            title: 'Patient Phone'
        },
        patient_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Email'
        },
        contact_method: {
            '$ref': '#/components/schemas/ContactMethod',
            default: 'phone'
        },
        appointment_date: {
            type: 'string',
            format: 'date',
            title: 'Appointment Date'
        },
        appointment_time: {
            type: 'string',
            maxLength: 5,
            title: 'Appointment Time'
        },
        status: {
            '$ref': '#/components/schemas/AppointmentStatus',
            default: 'pending'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        booking_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking Number'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        doctor_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doctor Name'
        }
    },
    type: 'object',
    required: ['doctor_id', 'patient_name', 'patient_phone', 'appointment_date', 'appointment_time', 'id'],
    title: 'AppointmentPublic'
} as const;

export const AppointmentPublicConfirmationSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        doctor_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doctor Name'
        },
        appointment_date: {
            type: 'string',
            format: 'date',
            title: 'Appointment Date'
        },
        appointment_time: {
            type: 'string',
            title: 'Appointment Time'
        },
        booking_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Booking Number'
        },
        patient_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Patient Email'
        },
        status: {
            '$ref': '#/components/schemas/AppointmentStatus'
        }
    },
    type: 'object',
    required: ['id', 'appointment_date', 'appointment_time', 'status'],
    title: 'AppointmentPublicConfirmation',
    description: `Minimal appointment response for the unauthenticated public endpoint.

Only exposes fields required by the booking confirmation page.
Does NOT expose PII fields like patient_phone, patient_name, or notes.`
} as const;

export const AppointmentStatusSchema = {
    type: 'string',
    enum: ['pending', 'confirmed', 'cancelled'],
    title: 'AppointmentStatus'
} as const;

export const AppointmentStatusUpdateSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/AppointmentStatus'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'AppointmentStatusUpdate'
} as const;

export const AppointmentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AppointmentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AppointmentsPublic'
} as const;

export const AvailableSlotSchema = {
    properties: {
        time: {
            type: 'string',
            title: 'Time'
        }
    },
    type: 'object',
    required: ['time'],
    title: 'AvailableSlot',
    description: 'A single available booking slot.'
} as const;

export const AvailableSlotsResponseSchema = {
    properties: {
        doctor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Doctor Id'
        },
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        slots: {
            items: {
                '$ref': '#/components/schemas/AvailableSlot'
            },
            type: 'array',
            title: 'Slots'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['doctor_id', 'date', 'slots', 'count'],
    title: 'AvailableSlotsResponse',
    description: 'Response containing all available slots for a doctor on a given date.'
} as const;

export const BlockedDateCreateSchema = {
    properties: {
        dates: {
            items: {
                type: 'string',
                format: 'date'
            },
            type: 'array',
            title: 'Dates'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['dates'],
    title: 'BlockedDateCreate'
} as const;

export const BlockedDatePublicSchema = {
    properties: {
        blocked_date: {
            type: 'string',
            format: 'date',
            title: 'Blocked Date'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        doctor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Doctor Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['blocked_date', 'id', 'doctor_id'],
    title: 'BlockedDatePublic'
} as const;

export const BlockedDatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BlockedDatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BlockedDatesPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ContactMethodSchema = {
    type: 'string',
    enum: ['phone', 'email', 'whatsapp', 'viber', 'zalo', 'telegram'],
    title: 'ContactMethod'
} as const;

export const DoctorAvailabilitiesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DoctorAvailabilityPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DoctorAvailabilitiesPublic'
} as const;

export const DoctorAvailabilityCreateSchema = {
    properties: {
        weekday: {
            '$ref': '#/components/schemas/Weekday'
        },
        start_time: {
            type: 'string',
            maxLength: 5,
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            maxLength: 5,
            title: 'End Time'
        },
        duration_minutes: {
            type: 'integer',
            maximum: 480,
            minimum: 5,
            title: 'Duration Minutes',
            default: 30
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['weekday', 'start_time', 'end_time'],
    title: 'DoctorAvailabilityCreate'
} as const;

export const DoctorAvailabilityPublicSchema = {
    properties: {
        weekday: {
            '$ref': '#/components/schemas/Weekday'
        },
        start_time: {
            type: 'string',
            maxLength: 5,
            title: 'Start Time'
        },
        end_time: {
            type: 'string',
            maxLength: 5,
            title: 'End Time'
        },
        duration_minutes: {
            type: 'integer',
            maximum: 480,
            minimum: 5,
            title: 'Duration Minutes',
            default: 30
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        doctor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Doctor Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['weekday', 'start_time', 'end_time', 'id', 'doctor_id'],
    title: 'DoctorAvailabilityPublic'
} as const;

export const DoctorAvailabilityUpdateSchema = {
    properties: {
        weekday: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Weekday'
                },
                {
                    type: 'null'
                }
            ]
        },
        start_time: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        duration_minutes: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 480,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Minutes'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'DoctorAvailabilityUpdate'
} as const;

export const DoctorCreateWithUserSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        specialization: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialization'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        experience_years: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experience Years'
        },
        consultation_duration: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 180,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Duration'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'DoctorCreateWithUser',
    description: `Schema for creating a doctor with automatic user creation.

This is the business-oriented input schema that combines
user credentials with doctor profile information.

The canonical field is \`specialty\`. The legacy field \`specialization\`
is also accepted for backward compatibility.`
} as const;

export const DoctorPublicSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        experience_years: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experience Years'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        photo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo Url'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        consultation_duration: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 180,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Duration'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['full_name', 'id', 'user_id'],
    title: 'DoctorPublic'
} as const;

export const DoctorUpdateSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        experience_years: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experience Years'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        photo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Photo Url'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        consultation_duration: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 180,
                    minimum: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Consultation Duration'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'DoctorUpdate'
} as const;

export const DoctorsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DoctorPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DoctorsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PatientSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['full_name'],
    title: 'Patient'
} as const;

export const PatientAccountActivateSchema = {
    properties: {
        phone: {
            type: 'string',
            maxLength: 20,
            title: 'Phone'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        confirm_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Confirm Password'
        }
    },
    type: 'object',
    required: ['phone', 'email', 'password', 'confirm_password'],
    title: 'PatientAccountActivate',
    description: 'Schema for activating a Patient account (linking to a new User).'
} as const;

export const PatientAccountActivateResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        patient: {
            '$ref': '#/components/schemas/PatientPublic'
        }
    },
    type: 'object',
    required: ['access_token', 'patient'],
    title: 'PatientAccountActivateResponse',
    description: 'Response after successful patient account activation.'
} as const;

export const PatientPublicSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['full_name', 'id'],
    title: 'PatientPublic',
    description: 'Public view of a Patient. Includes id and timestamps, excludes user_id linkage.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'doctor'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'doctor'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'doctor'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'doctor'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WeekdaySchema = {
    type: 'string',
    enum: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    title: 'Weekday'
} as const;