// This file is auto-generated by @hey-api/openapi-ts

export type AppointmentCreate = {
    doctor_id: string;
    patient_name: string;
    patient_phone: string;
    patient_email?: (string | null);
    contact_method?: ContactMethod;
    appointment_date: string;
    appointment_time: string;
    notes?: (string | null);
};

export type AppointmentPublic = {
    doctor_id: string;
    patient_name: string;
    patient_phone: string;
    patient_email?: (string | null);
    contact_method?: ContactMethod;
    appointment_date: string;
    appointment_time: string;
    status?: AppointmentStatus;
    notes?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type AppointmentsPublic = {
    data: Array<AppointmentPublic>;
    count: number;
};

export type AppointmentStatus = 'pending' | 'confirmed' | 'cancelled';

export type AppointmentStatusUpdate = {
    status: AppointmentStatus;
};

/**
 * A single available booking slot.
 */
export type AvailableSlot = {
    time: string;
};

/**
 * Response containing all available slots for a doctor on a given date.
 */
export type AvailableSlotsResponse = {
    doctor_id: string;
    date: string;
    slots: Array<AvailableSlot>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ContactMethod = 'phone' | 'email' | 'whatsapp' | 'viber' | 'zalo' | 'telegram';

export type DoctorAvailabilitiesPublic = {
    data: Array<DoctorAvailabilityPublic>;
    count: number;
};

export type DoctorAvailabilityCreate = {
    weekday: Weekday;
    start_time: string;
    end_time: string;
    duration_minutes?: number;
    is_active?: boolean;
};

export type DoctorAvailabilityPublic = {
    weekday: Weekday;
    start_time: string;
    end_time: string;
    duration_minutes?: number;
    is_active?: boolean;
    id: string;
    doctor_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type DoctorAvailabilityUpdate = {
    weekday?: (Weekday | null);
    start_time?: (string | null);
    end_time?: (string | null);
    duration_minutes?: (number | null);
    is_active?: (boolean | null);
};

/**
 * Schema for creating a doctor with automatic user creation.
 *
 * This is the business-oriented input schema that combines
 * user credentials with doctor profile information.
 *
 * The canonical field is `specialty`. The legacy field `specialization`
 * is also accepted for backward compatibility.
 */
export type DoctorCreateWithUser = {
    email: string;
    password: string;
    full_name: string;
    specialty?: (string | null);
    specialization?: (string | null);
    phone?: (string | null);
    bio?: (string | null);
    experience_years?: (number | null);
    consultation_duration?: (number | null);
    is_active?: boolean;
};

export type DoctorPublic = {
    full_name: string;
    specialty?: (string | null);
    experience_years?: (number | null);
    bio?: (string | null);
    photo_url?: (string | null);
    phone?: (string | null);
    consultation_duration?: (number | null);
    is_active?: boolean;
    id: string;
    user_id: string;
    email?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type DoctorsPublic = {
    data: Array<DoctorPublic>;
    count: number;
};

export type DoctorUpdate = {
    full_name?: (string | null);
    specialty?: (string | null);
    experience_years?: (number | null);
    bio?: (string | null);
    photo_url?: (string | null);
    phone?: (string | null);
    consultation_duration?: (number | null);
    is_active?: (boolean | null);
    email?: (string | null);
    password?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    created_at?: (string | null);
};

export type UserRole = 'admin' | 'doctor';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type Weekday = 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';

export type AppointmentsGetAvailableSlotsData = {
    /**
     * Target date in YYYY-MM-DD format
     */
    date: string;
    doctorId: string;
};

export type AppointmentsGetAvailableSlotsResponse = (AvailableSlotsResponse);

export type AppointmentsCreateAppointmentData = {
    requestBody: AppointmentCreate;
};

export type AppointmentsCreateAppointmentResponse = (AppointmentPublic);

export type AppointmentsReadAppointmentsData = {
    /**
     * Filter by appointment date (YYYY-MM-DD)
     */
    appointmentDate?: (string | null);
    /**
     * Filter by doctor UUID
     */
    doctorId?: (string | null);
    /**
     * Maximum records to return
     */
    limit?: number;
    /**
     * Number of records to skip
     */
    skip?: number;
    /**
     * Filter by appointment status
     */
    status?: (AppointmentStatus | null);
};

export type AppointmentsReadAppointmentsResponse = (AppointmentsPublic);

export type AppointmentsReadAppointmentData = {
    appointmentId: string;
};

export type AppointmentsReadAppointmentResponse = (AppointmentPublic);

export type AppointmentsDeleteAppointmentData = {
    appointmentId: string;
};

export type AppointmentsDeleteAppointmentResponse = (Message);

export type AppointmentsUpdateAppointmentStatusData = {
    appointmentId: string;
    requestBody: AppointmentStatusUpdate;
};

export type AppointmentsUpdateAppointmentStatusResponse = (AppointmentPublic);

export type AvailabilityReadDoctorAvailabilitiesData = {
    activeOnly?: boolean;
    doctorId: string;
    limit?: number;
    skip?: number;
};

export type AvailabilityReadDoctorAvailabilitiesResponse = (DoctorAvailabilitiesPublic);

export type AvailabilityCreateDoctorAvailabilityData = {
    doctorId: string;
    requestBody: DoctorAvailabilityCreate;
};

export type AvailabilityCreateDoctorAvailabilityResponse = (DoctorAvailabilityPublic);

export type AvailabilityUpdateDoctorAvailabilityData = {
    availabilityId: string;
    requestBody: DoctorAvailabilityUpdate;
};

export type AvailabilityUpdateDoctorAvailabilityResponse = (DoctorAvailabilityPublic);

export type AvailabilityDeleteDoctorAvailabilityData = {
    availabilityId: string;
};

export type AvailabilityDeleteDoctorAvailabilityResponse = (Message);

export type DoctorsReadDoctorsData = {
    limit?: number;
    skip?: number;
};

export type DoctorsReadDoctorsResponse = (DoctorsPublic);

export type DoctorsCreateDoctorData = {
    requestBody: DoctorCreateWithUser;
};

export type DoctorsCreateDoctorResponse = (DoctorPublic);

export type DoctorsReadDoctorsPublicData = {
    limit?: number;
    skip?: number;
};

export type DoctorsReadDoctorsPublicResponse = (DoctorsPublic);

export type DoctorsReadDoctorData = {
    doctorId: string;
};

export type DoctorsReadDoctorResponse = (DoctorPublic);

export type DoctorsUpdateDoctorData = {
    doctorId: string;
    requestBody: DoctorUpdate;
};

export type DoctorsUpdateDoctorResponse = (DoctorPublic);

export type DoctorsDeleteDoctorData = {
    doctorId: string;
    /**
     * Force deletion even if doctor has related records
     */
    force?: boolean;
};

export type DoctorsDeleteDoctorResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);