"""Add phone and consultation_duration to doctor

Revision ID: c2eb11e4d7d7
Revises: 2a7b9c3d1e5f
Create Date: 2026-06-15 13:27:22.428492

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c2eb11e4d7d7'
down_revision = '2a7b9c3d1e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('doctor', sa.Column('consultation_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor', 'consultation_duration')
    op.drop_column('doctor', 'phone')
    # ### end Alembic commands ###
