"""add_blocked_dates_table

Revision ID: e8f8789fb414
Revises: c8d4e5f6a7b8
Create Date: 2026-06-24 08:46:31.368444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e8f8789fb414'
down_revision = 'c8d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_dates',
    sa.Column('blocked_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'blocked_date', name='uq_blocked_date_per_doctor')
    )
    op.create_index(op.f('ix_blocked_dates_doctor_id'), 'blocked_dates', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocked_dates_doctor_id'), table_name='blocked_dates')
    op.drop_table('blocked_dates')
    # ### end Alembic commands ###
