/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as BookingConfirmationRouteImport } from './routes/booking/confirmation'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutDoctorsRouteImport } from './routes/_layout/doctors'
import { Route as LayoutAvailabilityRouteImport } from './routes/_layout/availability'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutDoctorsNewRouteImport } from './routes/_layout/doctors.new'
import { Route as LayoutDoctorsIdRouteImport } from './routes/_layout/doctors.$id'
import { Route as LayoutAvailabilityNewRouteImport } from './routes/_layout/availability.new'
import { Route as LayoutDoctorsIdEditRouteImport } from './routes/_layout/doctors.$id.edit'
import { Route as LayoutAvailabilityIdEditRouteImport } from './routes/_layout/availability.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => BookingRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDoctorsRoute = LayoutDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAvailabilityRoute = LayoutAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDoctorsNewRoute = LayoutDoctorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutDoctorsRoute,
} as any)
const LayoutDoctorsIdRoute = LayoutDoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutDoctorsRoute,
} as any)
const LayoutAvailabilityNewRoute = LayoutAvailabilityNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutAvailabilityRoute,
} as any)
const LayoutDoctorsIdEditRoute = LayoutDoctorsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutDoctorsIdRoute,
} as any)
const LayoutAvailabilityIdEditRoute =
  LayoutAvailabilityIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => LayoutAvailabilityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/booking': typeof BookingRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/availability': typeof LayoutAvailabilityRouteWithChildren
  '/doctors': typeof LayoutDoctorsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/availability/new': typeof LayoutAvailabilityNewRoute
  '/doctors/$id': typeof LayoutDoctorsIdRouteWithChildren
  '/doctors/new': typeof LayoutDoctorsNewRoute
  '/availability/$id/edit': typeof LayoutAvailabilityIdEditRoute
  '/doctors/$id/edit': typeof LayoutDoctorsIdEditRoute
}
export interface FileRoutesByTo {
  '/booking': typeof BookingRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/availability': typeof LayoutAvailabilityRouteWithChildren
  '/doctors': typeof LayoutDoctorsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/': typeof LayoutIndexRoute
  '/availability/new': typeof LayoutAvailabilityNewRoute
  '/doctors/$id': typeof LayoutDoctorsIdRouteWithChildren
  '/doctors/new': typeof LayoutDoctorsNewRoute
  '/availability/$id/edit': typeof LayoutAvailabilityIdEditRoute
  '/doctors/$id/edit': typeof LayoutDoctorsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/booking': typeof BookingRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/availability': typeof LayoutAvailabilityRouteWithChildren
  '/_layout/doctors': typeof LayoutDoctorsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/availability/new': typeof LayoutAvailabilityNewRoute
  '/_layout/doctors/$id': typeof LayoutDoctorsIdRouteWithChildren
  '/_layout/doctors/new': typeof LayoutDoctorsNewRoute
  '/_layout/availability/$id/edit': typeof LayoutAvailabilityIdEditRoute
  '/_layout/doctors/$id/edit': typeof LayoutDoctorsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/availability'
    | '/doctors'
    | '/settings'
    | '/booking/confirmation'
    | '/availability/new'
    | '/doctors/$id'
    | '/doctors/new'
    | '/availability/$id/edit'
    | '/doctors/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/booking'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/availability'
    | '/doctors'
    | '/settings'
    | '/booking/confirmation'
    | '/'
    | '/availability/new'
    | '/doctors/$id'
    | '/doctors/new'
    | '/availability/$id/edit'
    | '/doctors/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/booking'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/availability'
    | '/_layout/doctors'
    | '/_layout/settings'
    | '/booking/confirmation'
    | '/_layout/'
    | '/_layout/availability/new'
    | '/_layout/doctors/$id'
    | '/_layout/doctors/new'
    | '/_layout/availability/$id/edit'
    | '/_layout/doctors/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  BookingRoute: typeof BookingRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof BookingRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/doctors': {
      id: '/_layout/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof LayoutDoctorsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/availability': {
      id: '/_layout/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof LayoutAvailabilityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/doctors/new': {
      id: '/_layout/doctors/new'
      path: '/new'
      fullPath: '/doctors/new'
      preLoaderRoute: typeof LayoutDoctorsNewRouteImport
      parentRoute: typeof LayoutDoctorsRoute
    }
    '/_layout/doctors/$id': {
      id: '/_layout/doctors/$id'
      path: '/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof LayoutDoctorsIdRouteImport
      parentRoute: typeof LayoutDoctorsRoute
    }
    '/_layout/availability/new': {
      id: '/_layout/availability/new'
      path: '/new'
      fullPath: '/availability/new'
      preLoaderRoute: typeof LayoutAvailabilityNewRouteImport
      parentRoute: typeof LayoutAvailabilityRoute
    }
    '/_layout/doctors/$id/edit': {
      id: '/_layout/doctors/$id/edit'
      path: '/edit'
      fullPath: '/doctors/$id/edit'
      preLoaderRoute: typeof LayoutDoctorsIdEditRouteImport
      parentRoute: typeof LayoutDoctorsIdRoute
    }
    '/_layout/availability/$id/edit': {
      id: '/_layout/availability/$id/edit'
      path: '/$id/edit'
      fullPath: '/availability/$id/edit'
      preLoaderRoute: typeof LayoutAvailabilityIdEditRouteImport
      parentRoute: typeof LayoutAvailabilityRoute
    }
  }
}

interface LayoutAvailabilityRouteChildren {
  LayoutAvailabilityNewRoute: typeof LayoutAvailabilityNewRoute
  LayoutAvailabilityIdEditRoute: typeof LayoutAvailabilityIdEditRoute
}

const LayoutAvailabilityRouteChildren: LayoutAvailabilityRouteChildren = {
  LayoutAvailabilityNewRoute: LayoutAvailabilityNewRoute,
  LayoutAvailabilityIdEditRoute: LayoutAvailabilityIdEditRoute,
}

const LayoutAvailabilityRouteWithChildren =
  LayoutAvailabilityRoute._addFileChildren(LayoutAvailabilityRouteChildren)

interface LayoutDoctorsIdRouteChildren {
  LayoutDoctorsIdEditRoute: typeof LayoutDoctorsIdEditRoute
}

const LayoutDoctorsIdRouteChildren: LayoutDoctorsIdRouteChildren = {
  LayoutDoctorsIdEditRoute: LayoutDoctorsIdEditRoute,
}

const LayoutDoctorsIdRouteWithChildren = LayoutDoctorsIdRoute._addFileChildren(
  LayoutDoctorsIdRouteChildren,
)

interface LayoutDoctorsRouteChildren {
  LayoutDoctorsIdRoute: typeof LayoutDoctorsIdRouteWithChildren
  LayoutDoctorsNewRoute: typeof LayoutDoctorsNewRoute
}

const LayoutDoctorsRouteChildren: LayoutDoctorsRouteChildren = {
  LayoutDoctorsIdRoute: LayoutDoctorsIdRouteWithChildren,
  LayoutDoctorsNewRoute: LayoutDoctorsNewRoute,
}

const LayoutDoctorsRouteWithChildren = LayoutDoctorsRoute._addFileChildren(
  LayoutDoctorsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAvailabilityRoute: typeof LayoutAvailabilityRouteWithChildren
  LayoutDoctorsRoute: typeof LayoutDoctorsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAvailabilityRoute: LayoutAvailabilityRouteWithChildren,
  LayoutDoctorsRoute: LayoutDoctorsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface BookingRouteChildren {
  BookingConfirmationRoute: typeof BookingConfirmationRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingConfirmationRoute: BookingConfirmationRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  BookingRoute: BookingRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
